import { PUBLIC_SITE_URL } from "@/lib/site-url";

const baseUrl = PUBLIC_SITE_URL;

/**
 * Organization JSON-LD. Emitted on every page via the root layout.
 * Canonical identity record for MoedimAI.
 */
export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${baseUrl}/#organization`,
  name: "MoedimAI",
  alternateName: ["MoedimAI Verified", "Jaribu by MoedimAI"],
  url: baseUrl,
  logo: {
    "@type": "ImageObject",
    url: `${baseUrl}/images/moedimai-logo-light.png`,
  },
  description:
    "MoedimAI is the technology layer and AI supply chain platform driving Africa's bioeconomy. The platform benchmarks the end result back to the beginning and throughout the supply chain by connecting farmers, crops, value addition, processing, quality evidence, logistics, distribution, export, buyers, certifiers, funders, and programme operators on one governed operating graph.",
  slogan: "Technology layer and AI supply chain platform driving Africa's bioeconomy",
  foundingDate: "2024",
  founder: {
    "@type": "Person",
    "@id": `${baseUrl}/about#founder`,
    name: "Vivian Nwakah",
    jobTitle: "Founder and Chief Executive Officer",
    image: `${baseUrl}/images/vivian-nwakah-headshot.jpg`,
    sameAs: ["https://www.linkedin.com/in/viviannwakah/"],
  },
  address: [
    { "@type": "PostalAddress", addressCountry: "KE", addressLocality: "Nairobi" },
    { "@type": "PostalAddress", addressCountry: "NL", addressLocality: "Rotterdam" },
    {
      "@type": "PostalAddress",
      addressCountry: "US",
      addressLocality: "Dover",
      addressRegion: "DE",
    },
  ],
  knowsAbout: [
    "AI supply chain platform Africa",
    "Supply chain platform for Africa's bioeconomy",
    "Supply chain benchmarking Africa",
    "Technology layer for Africa bioeconomy",
    "End-to-end supply chain benchmarking",
    "Buyer-ready outcome benchmarking",
    "Verified African agricultural trade",
    "Bioeconomy supply chain platform",
    "African supply chain benchmarking",
    "African agricultural export programs",
    "Farmer network management",
    "Crop program management",
    "Harvest readiness benchmarking",
    "Crop benchmarking",
    "Agricultural distribution readiness",
    "Farm production management",
    "Trade infrastructure for agriculture",
    "Bioeconomy trade infrastructure",
    "Africa bioeconomy infrastructure",
    "Bioeconomy operating system",
    "Bioeconomy MRV platform",
    "Climate MRV for African agriculture",
    "AfCFTA agricultural trade infrastructure",
    "Verified bioeconomy supply chains",
    "Bioeconomy observatory software",
    "Bioeconomy standards and certification",
    "AI for Africa bioeconomy",
    "Bioeconomy agriculture technology",
    "Bioeconomy AI platform",
    "Agricultural bioeconomy operating systems",
    "Circular bioeconomy agriculture",
    "Biomass value chains",
    "Bio-based value chains",
    "Agricultural value addition",
    "Agro-processing value addition",
    "Steam distillation crop processing",
    "Drying and dehydration for agricultural products",
    "Cold press agricultural processing",
    "Agricultural logistics routing",
    "End-to-end agricultural supply chain",
    "Verifiable agricultural supply chains",
    "Specification-driven agricultural production",
    "Buyer-grade supply verification",
    "Financeable agricultural supply",
    "Multi-tenant agritech platforms",
    "Smallholder farm verification",
    "Satellite and weather intelligence for agriculture",
    "AI-assisted agricultural operating intelligence",
    "GC-MS chemotype verification",
    "African agricultural crop programs",
    "Aromatic and essential-oil crops",
    "Botanicals and natural ingredients",
    "Oilseeds and carrier oils",
    "Fresh produce and horticulture",
    "Grains, pulses, and staples",
    "Beverage and tree crops",
    "Spices and specialty crops",
    "Fiber, industrial, and biomass crops",
    "Agricultural supply chain",
    "Smallholder farmer programs",
    "EU organic certification",
    "USDA organic certification",
    "Kenyan agriculture",
    "Lot traceability",
    "Certificate of Analysis documentation",
  ],
  areaServed: [
    { "@type": "Country", name: "Kenya" },
    { "@type": "Place", name: "European Union" },
    { "@type": "Country", name: "United States" },
  ],
  contactPoint: {
    "@type": "ContactPoint",
    email: "vivian@moedim.ai",
    contactType: "sales",
    areaServed: ["EU", "US", "KE"],
    availableLanguage: ["English", "Swahili"],
  },
  makesOffer: [
    "AI supply chain platform driving Africa's bioeconomy",
    "End-to-end supply chain benchmarking",
    "Buyer-ready outcome benchmarking",
    "Bioeconomy trade infrastructure",
    "Bioeconomy supply chain platform",
    "Bioeconomy operating system",
    "Bioeconomy MRV platform",
    "Bioeconomy observatory software",
    "African crop program management",
    "Farmer network operations",
    "Crop benchmarking and harvest readiness",
    "Distribution and export readiness support",
    "Imani Pamoja trading and export route",
    "Agricultural bioeconomy operating system",
    "AI bioeconomy agriculture technology",
    "Value-addition processing modules",
    "Steam distillation, drying, and cold-press workflow support",
    "Logistics routing and end-to-end agricultural supply-chain control",
    "Specification-driven supply verification",
    "Buyer-ready traceability and documentation packets",
    "Satellite and weather operating intelligence",
    "Enterprise agricultural operating graph",
    "African agricultural crop program support",
  ],
  subjectOf: [
    {
      "@type": "CreativeWork",
      name: "The State of Verified Bioeconomy Infrastructure in Africa",
      url: `${baseUrl}/state-of-verified-bioeconomy-infrastructure-africa`,
    },
  ],
} as const;

/**
 * WebSite JSON-LD. Emitted alongside Organization.
 */
export const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${baseUrl}/#website`,
  url: baseUrl,
  name: "MoedimAI",
  description:
    "Technology layer and AI supply-chain benchmarking platform driving Africa's bioeconomy, including source records, value addition, verification, MRV, logistics routing, distribution, export, and buyer-ready supply.",
  publisher: { "@id": `${baseUrl}/#organization` },
  inLanguage: "en",
  hasPart: [
    `${baseUrl}/state-of-verified-bioeconomy-infrastructure-africa`,
    `${baseUrl}/africa-bioeconomy-infrastructure`,
    `${baseUrl}/bioeconomy-operating-system`,
    `${baseUrl}/ai-for-bioeconomy-value-chains`,
    `${baseUrl}/answers.md`,
    `${baseUrl}/llms.txt`,
  ],
} as const;
